#ifndef DEFINE_H
#define DEFINE_H

#define MENU_FILE_LOAD 1
#define MENU_FILE_SAVE 2
#define MENU_EXIT 3

#define MENU_INSERT_ALPHA 4
#define MENU_INSERT_BETA 5
#define MENU_INSERT_GAMMA 6
#define MENU_INSERT_DELTA 7 
#define MENU_INSERT_OMEGA 8
#define MENU_INSERT_EPSILON 9
#define MENU_INSERT_ZETA 10
#define MENU_INSERT_ETA 11
#define MENU_INSERT_THETA 12
#define MENU_INSERT_IOTA 13
#define MENU_INSERT_KAPPA 14
#define MENU_INSERT_LAMBDA 15
#define MENU_INSERT_MU 16
#define MENU_INSERT_NU 17
#define MENU_INSERT_XI 18
#define MENU_INSERT_OMICRON 19
#define MENU_INSERT_PI 20
#define MENU_INSERT_RHO 21
#define MENU_INSERT_SIGMA 22
#define MENU_INSERT_TAU 23
#define MENU_INSERT_UPSILON 24
#define MENU_INSERT_PHI 25
#define MENU_INSERT_CHI 26
#define MENU_INSERT_PSI 27

#endif